# Netlify configuration for Next.js app
[build]
  command = "npm run build"

[dev]
  command = "npm run dev"
  port = 8888

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
