// Lista de permissões baseada no JSON fornecido
import { RolePermissions } from "@/hooks/usePermissions";

export const permissionsList: RolePermissions[] = [
  {
    role: "administrator",
    permissions: {
      dashboard: true,
      pedidos: { visualizar: true, criar: true, editar: true },
      kanban: true,
      tasklist: true,
      notice: true,
      tabelaPrecos: true,
      calendar: true,
      usuarios: true,
      configuracoes: true,
      configuracoesKanban: true,
      configuracoesProducao: true,
      taskMoveBackward: true,
    },
  },
  {
    role: "manager",
    permissions: {
      dashboard: true,
      pedidos: { visualizar: true, criar: true, editar: true },
      kanban: true,
      tabelaPrecos: true,
      calendar: true,
      usuarios: true,
      configuracoes: true,
      configuracoesKanban: true,
      configuracoesProducao: true,
      taskMoveBackward: true,
    },
  },
  {
    role: "laboratory",
    permissions: {
      dashboard: true,
      pedidos: { visualizar: true, criar: true, editar: true },
      kanban: true,
      tasklist: false,
      notice: false,
      tabelaPrecos: true,
      calendar: true,
      usuarios: false,
      configuracoes: false,
      configuracoesKanban: false,
      configuracoesProducao: false,
      taskMoveBackward: false,
    },
  },
  {
    role: "doctor",
    permissions: {
      dashboard: true,
      pedidos: { visualizar: true, criar: true, editar: false },
      kanban: false,
      tasklist: false,
      notice: false,
      tabelaPrecos: true,
      calendar: false,
      usuarios: false,
      configuracoes: false,
      configuracoesKanban: false,
      configuracoesProducao: false,
      taskMoveBackward: false,
    },
  },
  {
    role: "technician",
    permissions: {
      dashboard: true,
      pedidos: { visualizar: true, criar: false, editar: true },
      kanban: true,
      tasklist: false,
      notice: false,
      tabelaPrecos: false,
      calendar: true,
      usuarios: false,
      configuracoes: false,
      configuracoesKanban: false,
      configuracoesProducao: false,
      taskMoveBackward: false,
    },
  },
  {
    role: "attendant",
    permissions: {
      dashboard: true,
      pedidos: { visualizar: true, criar: false, editar: false },
      kanban: false,
      tasklist: false,
      notice: false,
      tabelaPrecos: false,
      calendar: true,
      usuarios: false,
      configuracoes: false,
      configuracoesKanban: false,
      configuracoesProducao: false,
      taskMoveBackward: false,
    },
  },
];
